name: Deploy RustDesk Server

on:
  workflow_dispatch:  # Permet de déclencher manuellement le workflow
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Configurer l'environnement
      - name: Installer les dépendances requises
        run: |
          sudo apt update
          sudo apt install -y wget curl tar

      # Étape 2 : Télécharger RustDesk (hbbs et hbbr)
      - name: Télécharger RustDesk Server
        run: |
          mkdir -p ~/rustdesk-server
          cd ~/rustdesk-server
          wget https://github.com/rustdesk/rustdesk/releases/latest/download/hbbs-linux-amd64
          wget https://github.com/rustdesk/rustdesk/releases/latest/download/hbbr-linux-amd64
          chmod +x hbbs-linux-amd64 hbbr-linux-amd64

      # Étape 3 : Configurer RustDesk
      - name: Configurer RustDesk Server
        run: |
          cd ~/rustdesk-server
          # Créer un certificat auto-signé pour la communication sécurisée
          openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=localhost"
          
          # Générer les clés pour le serveur
          ./hbbs-linux-amd64 -k _

      # Étape 4 : Lancer les services hbbs et hbbr
      - name: Lancer le serveur RustDesk
        run: |
          cd ~/rustdesk-server
          nohup ./hbbs-linux-amd64 -r 21115:21116 > hbbs.log 2>&1 &
          nohup ./hbbr-linux-amd64 > hbbr.log 2>&1 &
          echo "RustDesk Server déployé avec succès !"

      # Étape 5 : Vérification des services
      - name: Vérifier les services RustDesk
        run: |
          ps aux | grep hbbs
          ps aux | grep hbbr
